title:             YoHwanChoi
email:             dyghks1994@gmail.com
description:       Github Page
author:            Start Page
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://dyghks1994.github.io"

# Social Profiles
twitter_username:  YoHwanChoi
github_username:   dyghks1994
facebook_username: YoHwanChoi

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
